### ISSUE TITLE
Back to bootstrap?

### ISSUE THREAD

**Issue by pdonorio** [pdonorio/restangulask#38]
Of what we have experienced so far, we noticed that the only css framework really supported by other libraries is bootstrap.

There is a new material design rappresentation based on bootstrap:
http://mdbootstrap.com/live/_MDB/index/docs/presentation-free/lp-components.html

It has some premium on-pay features.
What we should do within this week is evaluate if this plugin is compatible with what we have: angularjs calls and formly. 

note: bootstrap has arrived to alpha 4 of their new release v4 (see the [announcement](http://blog.getbootstrap.com/2016/09/05/bootstrap-4-alpha-4/))

**Comment by pdonorio** [comment]
A test can be created with a simple web page and some cdn:
- jquery 3
- angular 1.5
- boostrap 3 (or 4?)
- restangulask (or whatever may help you work models into bootstrap forms)
- formly
- formly-bootstrap-templates

Then go ahead and test, for instance, a select and also autocomplete.

**Comment by mdantonio** [comment]
I don't think that Material Design for Bootstrap can really allow for autocomplete

Since it is based on jquery, even if implemented, it will require an integration between jquery (autocomplete) and angualrjs (data retrieve via service->api)... this could be painful.

MDB is a really exciting project but i'm not really convinced that this half-blood framework will simplify our life.
Are we really sure to maintain the choice of Material Design?

**Comment by pdonorio** [comment]
I'm open :) 
Rebuilding the framework we can make whatever choice we want on the front-end.

We can choose bootstrap and apply a nice theme, also miming material design.
The only thing I really want is `cards`, and especially cute ones :)

**Comment by pdonorio** [comment]
Note: whatever we choose, let's make sure with a prototype that select and autocomplete works, anyway.
